name: APK Build flet v0.27.6

on:
  # Runs on push to any of the below branches
  push:
    branches:
      - main

  # Runs on pull request events that target one of the below branches
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab of the repository
  workflow_dispatch:

env:
  # https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Python version to use
  PYTHON_VERSION: 3.12.8

  # flet-cli version to install for `flet build`
  FLET_CLI_VERSION: 0.27.6

  # Ensures Python uses UTF-8 encoding by default
  PYTHONUTF8: 1

  # Disables rich text formatting in Flet CLI output
  FLET_CLI_NO_RICH_OUTPUT: 1

  # Disables progress bars when using UV
  UV_NO_PROGRESS: 1

  # Flutter version to use for building the APK
  FLUTTER_VERSION: 3.27.4

jobs:
  build-apk-v0_27_6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==$FLET_CLI_VERSION

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      - name: Install Android SDK components
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Patch for linux build
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Flet Build APK
        run: |
          cd tests/cache-pages-v0.27.6
          flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-v0.27.6-v0.3.0
          path: tests/cache-pages-v0.27.6/build/apk/app-release.apk
          if-no-files-found: warn
          overwrite: false
